openapi: 3.0.3
info:
  title: MatchWise All APIs
  description: REST APIs for the entire matchwise application
  version: '1.0'

servers:
  - url: http://localhost:9000
    description: Local development environment

paths:
  /login:
    post:
      operationId: user-login
      description: API for login
      responses:
        200:
          description: Succesfully posted the details
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "/#/components/schemas/Login"
        401:
          description: Authentication Error
          content:
            "application/json":
              schema:
                type: object
                $ref: "/#/components/schemas/Error"
        500:
          description: Authentication Error
          content:
            "application/json":
              schema:
                type: object
                $ref: "/#/components/schemas/Error"
    

      


components:
  schemas:
    Login:
      type: object
      properties:
        userName: 
          type: string
        password: 
          type: string
        role: 
          type: string
       

 
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string